### ISSUE TITLE
External Link not working

### ISSUE THREAD

**Issue by roystone** [ChrisWojcik/single-page-nav#12]
I have a external link blog, and contact, navigation is working fine and scrolling nicely but when i click on blog and contact it did't go to their external page.

 // The actual plugin
    $('#nav').singlePageNav({
        offset: $('.navigation-box').outerHeight(),
        filter: ':not(.external)',
        currentClass: 'hover-class',
        updateHash: true,
        beforeStart: function () {
            console.log('begin scrolling');
        },
        onComplete: function () {
            console.log('done scrolling');
        }
    });

**Comment by fmms** [comment]
I just experienced the same issue.
add class="external" do my links that are not just scrolling on the one pager solved it for me.

**Comment by yonisoka** [comment]
Guys please give a guide on how to add class external. and how to fix external link issue

**Comment by roystone** [comment]
Use Class with anchor external
`<a href="http://abc.com" class="external">External Link</a>`

**Comment by yonisoka** [comment]
@roystone  im using joomla
here is the output:
<a href="/index.php/jobseeker-control-panel" target="_blank" class="menu-item">
joomla automatically include "menu-item" class which should be "external", i try also to add css link module "external" the output is class="menu-item external"
