### ISSUE TITLE
Prevents linking to other pages from the navigation

### ISSUE THREAD

**Issue by mzhKU** [ChrisWojcik/single-page-nav#29]
If I apply the singlePageNav function to a navigation that also links to other pages (not just sections on the current page), then single Page nav seems to prevent accessing the other page. Is there a solution to this?

**Comment by noblesilence** [comment]
You can add `filter`:
1. Add `external` class to those links in HTML code.
2. `$('#navigation-bar').singlePageNav({'filter': ':not(.external)'});`

> 'filter' - By default, the plugin will be applied to all links within the container, use this to filter out certain links using jquery's built in filter method (e.g. ':not(.external)')

**Comment by mzhKU** [comment]
I had the filter active but seems not to work... seen this before?

**Comment by noblesilence** [comment]
Can you share your code so I can take a look?
